"""Module V: Fintech Ecosystem

Revision ID: 31796d76c0a7
Revises: 62bd0a341513
Create Date: 2026-06-28 19:35:51.670620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31796d76c0a7'
down_revision: Union[str, Sequence[str], None] = '62bd0a341513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_workspace_id'), 'payment_links', ['workspace_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('nfe_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sefaz_link', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_workspace_id'), 'invoices', ['workspace_id'], unique=False)
    op.create_table('payment_charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('charge_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('gateway_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_charges_gateway_id'), 'payment_charges', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_payment_charges_workspace_id'), 'payment_charges', ['workspace_id'], unique=False)
    op.create_table('receivable_anticipations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('payment_charge_id', sa.UUID(), nullable=False),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('discount_fee', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_charge_id'], ['payment_charges.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivable_anticipations_workspace_id'), 'receivable_anticipations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivable_anticipations_workspace_id'), table_name='receivable_anticipations')
    op.drop_table('receivable_anticipations')
    op.drop_index(op.f('ix_payment_charges_workspace_id'), table_name='payment_charges')
    op.drop_index(op.f('ix_payment_charges_gateway_id'), table_name='payment_charges')
    op.drop_table('payment_charges')
    op.drop_index(op.f('ix_invoices_workspace_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_payment_links_workspace_id'), table_name='payment_links')
    op.drop_table('payment_links')
    # ### end Alembic commands ###
