"""Sprint 2: Open Finance and AI

Revision ID: 95137e69c3ae
Revises: cc16cf771c9a
Create Date: 2026-06-28 19:24:06.320454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95137e69c3ae'
down_revision: Union[str, Sequence[str], None] = 'cc16cf771c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('agency', sa.String(length=20), nullable=True),
    sa.Column('integration_id', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_integration_id'), 'bank_accounts', ['integration_id'], unique=True)
    op.create_index(op.f('ix_bank_accounts_workspace_id'), 'bank_accounts', ['workspace_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statements_account_id'), 'bank_statements', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_external_id'), 'bank_statements', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statements_external_id'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_account_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_bank_accounts_workspace_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_integration_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
