"""Sprint 1: Invitations and AuditLogs

Revision ID: cc16cf771c9a
Revises: 1d2467b4c74a
Create Date: 2026-06-28 19:17:28.379184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc16cf771c9a'
down_revision: Union[str, Sequence[str], None] = '1d2467b4c74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('transactions', 'audit_log')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('workspaces_cnpj_key'), 'workspaces', type_='unique')
    op.drop_index(op.f('ix_workspaces_cnpj'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_cnpj'), 'workspaces', ['cnpj'], unique=True)
    
    # --- ENTERPRISE SPRINT 1: AUDIT TRAIL AND RLS ---
    
    # 1. Audit Trigger Function
    op.execute("""
    CREATE OR REPLACE FUNCTION log_transaction_audit()
    RETURNS TRIGGER AS $$
    BEGIN
        IF (TG_OP = 'DELETE') THEN
            INSERT INTO audit_logs (transaction_id, action, old_values, created_at)
            VALUES (OLD.id, 'DELETE', row_to_json(OLD)::jsonb, now());
            RETURN OLD;
        ELSIF (TG_OP = 'UPDATE') THEN
            INSERT INTO audit_logs (transaction_id, action, old_values, new_values, created_at)
            VALUES (NEW.id, 'UPDATE', row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, now());
            RETURN NEW;
        ELSIF (TG_OP = 'INSERT') THEN
            INSERT INTO audit_logs (transaction_id, action, new_values, created_at)
            VALUES (NEW.id, 'INSERT', row_to_json(NEW)::jsonb, now());
            RETURN NEW;
        END IF;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # 2. Attach trigger to transactions
    op.execute("""
    CREATE TRIGGER trg_audit_transactions
    AFTER INSERT OR UPDATE OR DELETE ON transactions
    FOR EACH ROW EXECUTE FUNCTION log_transaction_audit();
    """)
    
    # 3. Enable RLS on new tables
    op.execute("ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;")
    
    # 4. RLS Policies
    op.execute("""
    CREATE POLICY "Tenant isolation for invitations"
    ON invitations FOR ALL
    USING (workspace_id = current_setting('app.current_workspace_id', true)::uuid);
    """)
    
    op.execute("""
    CREATE POLICY "Tenant isolation for audit_logs"
    ON audit_logs FOR ALL
    USING (transaction_id IN (SELECT id FROM transactions WHERE workspace_id = current_setting('app.current_workspace_id', true)::uuid));
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_cnpj'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_cnpj'), 'workspaces', ['cnpj'], unique=False)
    op.create_unique_constraint(op.f('workspaces_cnpj_key'), 'workspaces', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('transactions', sa.Column('audit_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
